#!/bin/bash

# set -o verbose
# set -o xtrace

if [[ -z $1 ]]; then
    echo 'Usage: config-remote <repo-path> <host> [<rsync-remote-shell>]'
    exit 1
fi

REPO_PATH="$(realpath $1)"
REPO_NAME="$(basename $REPO_PATH)"
HOST="$2"
SSH="${3:-ssh}"
RSYNC="rsync --exclude=.gitignore --exclude=.git --exclude=build -a --delete"

if [[ ! -x "$REPO_PATH/scripts/$(basename $0)" ]]; then
    echo 'Bad repo path.'
    exit 1
fi

if [[ -z "$HOST" ]]; then
    echo 'Bad host.'
    exit 1
fi

$RSYNC -e "$SSH" $REPO_PATH $HOST:~

$SSH $HOST 'cd ~/'"$REPO_NAME"' && \
            make && make install && \
            ./scripts/install-vim-plug && \
            ./scripts/install-vim-plug-plugins'
