#!/bin/bash

# set -o verbose
# set -o xtrace

if [[ -z $1 ]]; then
    echo 'Usage: config <repo-path> [<host>] [<rsync-remote-shell>]'
    exit 1
fi

# REPO_PATH="$(realpath $1)"
REPO_PATH="$(readlink -f $1)"
REPO_NAME="$(basename $REPO_PATH)"
HOST="$2"
REMOTE_SHELL="$3"
RSYNC="rsync --exclude=.gitignore --exclude=.git --exclude=build -a --delete"

if [[ ! -x "$REPO_PATH/scripts/$(basename $0)" ]]; then
    echo 'Bad repo path.'
    exit 1
fi

if [[ -z "$HOST" ]]; then
    cd "$REPO_PATH"
    make && make install && make extra-install
else
    $RSYNC ${REMOTE_SHELL:+-e} ${REMOTE_SHELL:+"$REMOTE_SHELL"} "$REPO_PATH" "$HOST:~"
    ${REMOTE_SHELL:-ssh} $HOST 'cd ~/'"$REPO_NAME"' && \
                                make && make install && make extra-install'
fi
