#!/bin/bash

pip3 install jupyter
pip3 install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user

pip3 install pipenv
pip3 install flake8

pip3 install jupyterlab
jupyter labextension install @jupyter-widgets/jupyterlab-manager
