#!/bin/bash

brew install bash
brew install coreutils
brew install less
brew install findutils
brew install grep
brew install gnu-sed
brew install vim

brew install tree
brew install highlight
brew install tmux

# See also the `gr` in *30_aliases.sh*.
brew install ripgrep  # Also in >= Ubuntu 20.04 and Debian 10.

# See also the `fn` in *30_aliases.sh*.
brew install fd  # Also in >= Ubuntu 20.04 and Debian 10.

# See also the `hl` in *30_aliases.sh*.
brew install bat  # Also in >= Ubuntu 20.04 and Debian 11.

brew install jq  # Also in >= Ubuntu 14.04 and Debian 8.
brew install gron  # Also in >= Ubuntu 20.04 and Debian 10.

brew install git
brew install python
brew install nodejs
brew install pyenv

brew install mtr
brew install nmap
