#!/bin/bash

# won't use nvim anymore
# if [[ -x $(command -v nvim) ]]; then
if false; then
    if [[ ! -f ~/.config/nvim/autoload/plug.vim ]]; then
        curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi
else
    if [[ ! -f ~/.vim/autoload/plug.vim ]]; then
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi
fi
